# -*- coding: utf-8 -*-
"""exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma3WqDAKyaI-Lb6fw6OVLDFfq2DuxfFv
"""

n=1
coches=("chevi","lamborjetta","fork","march")
for coche in coches: # en el ciclo se usa
  print(n,".",coche)
  n+=1 # en la parte de aqui se usa un contador que suma de 1 en 1.
print(n, ". salir")
opcion= int(input(' elije una opcion'))
print(coches[opcion-1])

estu=[
    ["ana", "beto", "carlos", "diego"],
    [9,8,9,19],
    ["Gdl","cdmx","Son","Nay"]
]
print(estu[0][0])

# Datos del inventario de la tienda de mariscos
inventario = {
    "Fish": {'Tilapia': 25, 'bagre': 15, 'salmon': 2},
    "seafood": {'Pulpo': 7, 'ostión': 40}
}

print("--- Inventario de Pescados y Mariscos ---")
print("-" * 55)


for categoria_nombre, productos_en_categoria in inventario.items():
    print(f"\nCategoría: {categoria_nombre.capitalize()}")
    for producto, cantidad in productos_en_categoria.items():

        print(f"{producto.capitalize():<10} | {'*' * cantidad} ({cantidad})")

print("-"*55)
<<<<<<< HEAD
# hola compañeros :)
=======
"gato"
>>>>>>> 45aa1fdc44149743ed6cadd9b17460f942c125e5
